#!/usr/bin/bash

yay -S appimagelauncher
yay -S visual-studio-code-bin 
yay -S mongodb-compass
yay -S mongodb-bin
yay -S mongodb-tools-bin
yay -S pamac-aur
yay -S pamac-tray-appindicator
yay -S php-mcrypt
yay -S pivx-qt
yay -S postman-bin

#Internet
yay -S brave-bin
yay -S google-chrome
drive-bin
zoom

#Security
yay -S ntop